package com.isteer.jdbc.enums;

public enum TicketEnums {
	
	 PASSWORD_INVAILD_EXCEPTION(1993,"ENTER THE CORRECT PASSWORD"),
     REGISTERATION_SUCESS(1221,"USER REGISTERATION SUCCESSFULL" ),
     REGISTERATION_FAILED(9923,"REGISTERATION FAILED, CUSTOMER ALREADY EXITS"),
     ROLE_ELEVATION_SUCCESS(1890,"ROLE AS BEEN ELEVATED"),
     ROLE_ELEVATION_FAILED(9871,"ROLE ELEVATION FAILED"),
     ROLE_DEMOTE_SUCCESS(1891, "ROLE AS BEEN DEELEVATED"),
     ROLE_DEMOTE_FAILED(9231,"ROLE CANNOT BE DEELEVATED"),
     NEW_ROLE_ADD(1213,"NEW ROLE HASBEEN ADDED"),
     NEW_ROLE_FAILED(9031,"NEW ROLE ADDED FAILED"),
     ROLE_REMOVED_MESSAGE(1341,"ROLE REMOVED SUCCESSFULLY"),
     ROLE_NOT_REMOVE(9567, "ROLE NOT FOUND ! ROLE CANNOT BE REMOVED"),
     ADD_URL_MESSAGE(1231,"URL PERMISSION ADDED"),
     ADD_URL_ERROR(9012,"URL PERMISSION FAILED"),
     REMOVE_URL_MESSAGE(1251,"REMOVE URL PERMISSION SUCCESSFUL"),
     REMOVE_URL_ERROR(9021,"REMOVE URL PERMISSION FAILED"),
	 DUPLICATE_URL_MESSAGE(9873, "DUPLICATE ENTRY CANNOT BE ALLOWED"),
	 TICKET_SUBMITTED_SUCCESSFULLY(1253, "TICKET SUBMITTED SUCCESSFULLY"),
	 TICKET_FAILED(9234,"TICKET SUBMISSION FAILED"),
	 USER_NOT_FOUND(9340, "USER NOT FOUND"),
	 AUTHORIZATION_DEINED(9321,"ACCESS DENIED ! CONTACT ADMIN"),
	 EMPTY_DATA_EXCEPTION(9821, "NO SUCH DATA FOUND , RETRY WITH ANOTHER"),
	 RUNTIME_EXCEPTION(9821,"RUNTIME EXCEPTION"),
	 TICKET_ASSIGNED(1760,"TICKET ASSINGED SUCCESSFULLY"),
	 TICKET_NOT_ASSIGED(9567,"TICKET ASSIGNED FAILED"),
	 STATUS_SET(1876, "STATUS SET SUCCESSFULL"),
	 STATUS_NOT_SET(9087,"STATUS NOT SET"),
	 HTTP_METHOD_ADD(1234,"HTTP METHOD ADDED"),
	 HTTP_METHOD_ADD_FAILED(9231,"HTTP METHOD ADD FAILED"),
	 HTTP_METHOD_REMOVE(1022,"HTTP METHOD REMOVED"),
	 HTTP_REMOVE_FAILED(9021,"HTTP METHOD REMOVE FAILED");
	
	
	
	int statusCode;
	String statusMessage;
	public int getStatusCode() {
		return statusCode;
	}
	public void setStatusCode(int statusCode) {
		this.statusCode = statusCode;
	}
	public String getStatusMessage() {
		return statusMessage;
	}
	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}
	
	
	private TicketEnums(int statusCode, String statusMessage) {
		this.statusCode = statusCode;
		this.statusMessage = statusMessage;
	} 

}
